server:
  port: 7001
  
  
eureka:
  instance:
    hostname: eureka7001.com # eureka服务端的实例名称
  client:
    register-with-eureka: false # 不向服务中心注册自己
    fetch-registry: false # 表示自己端就是注册中心,不需要同步其他eureka服务节点的数据
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/
#      ,http://eureka7003.com:7003/eureka/
  