server:
 port: 8001


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.mao.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: SpringcloudDemo-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/mydb01?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    
    
eureka:
  client: #客户端注册到服务中心列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
#      ,http://eureka7003.com:7003/eureka
  instance:
    instance-id: SpringcloudDemo-dept-8001-hystrix
    prefer-ip-address: true #访问路径显示成ip地址
   
info:
  app.name: springcloudDemo









